<div @click.away="open = false" class="flex flex-col flex-shrink-0 w-full text-gray-700 bg-white md:w-64 dark-mode:text-gray-200 dark-mode:bg-gray-800" x-data="{ open: false }">
    <nav :class="{'block': open, 'hidden': !open}" class="flex-grow px-4 pb-4 md:block md:pb-0 md:overflow-y-auto">
        <a class="block px-4 py-2 mt-2 text-sm font-semibold text-gray-900 {{ Route::currentRouteNamed('admin.roles.index') ? 'bg-gray-200' : '' }} rounded-lg dark-mode:bg-gray-700 dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="{{ route('admin.roles.index') }}">Roles</a>

        <a class="block px-4 py-2 mt-2 text-sm font-semibold text-gray-900 {{ Route::currentRouteNamed('admin.permissions.index') ? 'bg-gray-200' : '' }} rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="{{ route('admin.permissions.index') }}">Permissions</a>

        <a class="block px-4 py-2 mt-2 text-sm font-semibold text-gray-900 {{ Route::currentRouteNamed('admin.users.index') ? 'bg-gray-200' : '' }} rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="{{ route('admin.users.index') }}">Users</a>

        <a class="block px-4 py-2 mt-2 text-sm font-semibold text-gray-900 {{ Route::currentRouteNamed('admin.admins.index') ? 'bg-gray-200' : '' }} rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="{{ route('admin.admins.index') }}">Admins</a>

        <a class="block px-4 py-2 mt-2 text-sm font-semibold text-gray-900 {{ Route::currentRouteNamed('admin.posts.index') ? 'bg-gray-200' : '' }} rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="{{ route('admin.posts.index') }}">Posts</a>

        <a class="block px-4 py-2 mt-2 text-sm font-semibold text-gray-900 {{ Route::currentRouteNamed('admin.livewirecounter.index') ? 'bg-gray-200' : '' }} rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="{{ route('admin.livewirecounter.index') }}">LiveWire</a>

        <a class="block px-4 py-2 mt-2 text-sm font-semibold text-gray-900 {{ Route::currentRouteNamed('admin.employees.index') ? 'bg-gray-200' : '' }} rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="{{ route('admin.employees.index') }}">Employees</a>

        <a class="block px-4 py-2 mt-2 text-sm font-semibold text-gray-900 {{ Route::currentRouteNamed('admin.inventory.index') ? 'bg-gray-200' : '' }} rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="{{ route('admin.inventory.index') }}">Inventory</a>

        <a class="block px-4 py-2 mt-2 text-sm font-semibold text-gray-900 {{ Route::currentRouteNamed('admin.barcodes.index') ? 'bg-gray-200' : '' }} rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="{{ route('admin.barcodes.index') }}">Barcodes</a>
    </nav>
</div>
